# Generated by Django 2.2.6 on 2019-10-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=500)),
                ('img_url', models.CharField(max_length=500)),
                ('alt_text', models.CharField(max_length=500)),
                ('short_desc', models.CharField(max_length=50)),
                ('temp', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
