# Generated by Django 2.2.6 on 2019-10-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather_app', '0002_auto_20191024_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='extended',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
